- name: Ensure pull secret exists
  ansible.builtin.set_fact:
    b64auth: "{{ (mirror_registry_user + ':' + mirror_registry_password) | b64encode }}"

- name: Ensure pull secret exists
  ansible.builtin.set_fact:
    ocp_pull_secret: '{ "auths": { "{{ mirror_registry_hostname }}": { "auth": "{{ b64auth }}","email": "dontmindme@example.com" }}}'
