- name: Generate an OpenSSH keypair
  community.crypto.openssh_keypair:
    path: "{{ config_path }}/id_ed25519"
    type: ed25519
  when: ocp_ssh_pub is undefined or
        ocp_ssh_pub == None or
        ocp_ssh_pub| length == 0

- name: load ssh pub_key to fact
  ansible.builtin.set_fact:
    ocp_ssh_pub: "{{ lookup('ansible.builtin.file', config_path + '/id_ed25519.pub' ) }}"
  when: ocp_ssh_pub is undefined or
      ocp_ssh_pub == None or
      ocp_ssh_pub| length == 0

- name: debug pubkey
  ansible.builtin.debug:
    var: ocp_ssh_pub
  tags:
    - never
    - debug
