---
- name: Install packages
  become: true
  ansible.builtin.package:
    name:
      - nmstate
    state: present
  tags:
    - packages

- name: ensure ocp_tools directory
  become: true
  ansible.builtin.file:
    state: directory
    name: "{{ item }}"
    mode: 0700
    owner: "{{ mirror_data_dir_group }}"
    group: "{{ mirror_data_dir_owner }}"
  loop:
    - "{{ lookup('ansible.builtin.env', 'HOME') }}/ocp_tools"
    - "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/bin"
    - "{{ lookup('ansible.builtin.env', 'HOME') }}/ocp_tools/mirror-registry"
    - "{{ mirror_registry_data_dir }}"
    - "{{ mirror_data_dir }}"
  tags:
    - packages

- name: download client tools
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/ocp_tools/."
  loop:
    - "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocp_version }}/oc-mirror.tar.gz"
    - "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocp_version }}/openshift-client-linux-{{ ocp_version }}.tar.gz"
    - "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocp_version }}/openshift-install-linux-{{ ocp_version }}.tar.gz"
    - "https://developers.redhat.com/content-gateway/file/pub/openshift-v4/clients/mirror-registry/{{ mirror_registry_version }}/mirror-registry.tar.gz"
  tags:
    - packages

- name: extract client tools
  ansible.builtin.unarchive:
    src: "{{ lookup('ansible.builtin.env', 'HOME') }}/ocp_tools/{{ item.tar }}"
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/bin"
    creates: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/bin/{{ item.bin }}"
  loop:
    - tar: oc-mirror.tar.gz
      bin: oc-mirror
    - tar: "openshift-client-linux-{{ ocp_version }}.tar.gz"
      bin: oc
    - tar: "openshift-install-linux-{{ ocp_version }}.tar.gz"
      bin: openshift-install
  tags:
    - packages

- name: extract mirror-registry
  ansible.builtin.unarchive:
    src: "{{ lookup('ansible.builtin.env', 'HOME') }}/ocp_tools/mirror-registry.tar.gz"
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/ocp_tools/mirror-registry"
  tags:
    - packages

- name: ensure execution permissions
  ansible.builtin.file:
    state: file
    mode: 0755
    name: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/bin/{{ item }}"
  loop:
    - kubectl
    - oc-mirror
    - openshift-install
    - oc
  tags:
    - packages

- name: include tasks for operatorversions (rh index)
  ansible.builtin.import_tasks: create_operator_versions.yaml
  vars:
    operator_catalog: "registry.redhat.io/redhat/redhat-operator-index"
    operators: "{{ rh_operators }}"
  run_once: false
  when: ( rh_operators is defined ) and
        ( rh_operators | length > 0 )

- name: set operatorversions (rh index)
  ansible.builtin.set_fact:
    rh_operator_packages: "{{ operator_versions }}"

- name: include tasks for operatorversions (certified index)
  ansible.builtin.import_tasks: create_operator_versions.yaml
  vars:
    operator_catalog: "registry.redhat.io/redhat/certified-operator-index"
    operators: "{{ certified_operators }}"
  when: ( certified_operators is defined ) and
        ( certified_operators | length > 0 )

- name: set operatorversions (certified index)
  ansible.builtin.set_fact:
    certified_operator_packages: "{{ operator_versions }}"

- name: generate ImageSetConfiguration
  ansible.builtin.template:
    src: ./templates/imagesetconfiguration.yaml.j2
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/ocp_tools/mirror-registry/imagesetconfiguration.yaml"
    mode: 0644
