---
- name: include package download and configuration
  ansible.builtin.import_tasks: create_packages.yaml

- name: include tasks for operatorversions (rh index)
  ansible.builtin.import_tasks: create_operator_versions.yaml
  vars:
    operator_catalog: "registry.redhat.io/redhat/redhat-operator-index"
    operators: "{{ rh_operators }}"
  run_once: false
  when: ( rh_operators is defined ) and
        ( rh_operators | length > 0 )

- name: set operatorversions (rh index)
  ansible.builtin.set_fact:
    rh_operator_packages: "{{ operator_versions }}"

- name: include tasks for operatorversions (certified index)
  ansible.builtin.import_tasks: create_operator_versions.yaml
  vars:
    operator_catalog: "registry.redhat.io/redhat/certified-operator-index"
    operators: "{{ certified_operators }}"
  when: ( certified_operators is defined ) and
        ( certified_operators | length > 0 )

- name: set operatorversions (certified index)
  ansible.builtin.set_fact:
    certified_operator_packages: "{{ operator_versions }}"
  when: ( certified_operators is defined ) and
        ( certified_operators | length > 0 )

- name: generate ImageSetConfiguration
  ansible.builtin.template:
    src: ./templates/imagesetconfiguration.yaml.j2
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/ocp_tools/mirror-registry/imagesetconfiguration.yaml"
    mode: 0644

- name: mirror to local disk
  ansible.builtin.command:
    cmd: oc-mirror --config "{{ lookup('ansible.builtin.env', 'HOME') }}/ocp_tools/mirror-registry/imagesetconfiguration.yaml" "file://{{ mirror_data_dir }}"
